### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by NicholasJohn16** [IliasHad/makerlapse-app#18]
I can get the app to start. After that, I can click on the icon in the system tray and get the window to open up, but I can't seem to move the window at all and if the system tray closes, the window disappears as well. Clicking the record button is a bit difficult, but I can get it to work, but when I click stop, it never creates a video. The "video" screen stays at 0%.

Seems like a neat app that I wouldn't mind giving a try. Is there anything I can do to help debug these issues?

Output of `yarn start`:
``` 
yarn run v1.22.4
$ concurrently "cross-env PORT=9000 BROWSER=none yarn react-start" "wait-on http://localhost:9000 && electron ."      
$ react-scripts start
[0] Starting the development server...
[0]
[0] Compiled with warnings.
[0]
[0] ./src/Components/content.js
[0]   Line 63:6:  React Hook useEffect has missing dependencies: 'screenList', 'selectOption', 'selectedScreen', 'sele
ctedWindow', and 'windowList'. Either include them or remove the dependency array  react-hooks/exhaustive-deps        
[0]
[0] Search for the keywords to learn more about each warning.
[0] To ignore, add // eslint-disable-next-line to the line before.
[0]
[1] ```

**Comment by polyglotdev** [comment]
What I find to be odd about this error is that the version of node that `npm install` with actually changes the error. I have killed node modules three times and npm installed again with 12.18.0, 13.0.0 and 14.5.0. The recent error on 14.5.0:
```bash
./src/Components/content.js
Line 63:6:  React Hook useEffect has missing dependencies: 'isRecording', 'screenList', 'selectOption', 'selectedScreen', 'selectedWindow', and 'windowList'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
```

**Comment by polyglotdev** [comment]
The electron app shows in the top toolbar, but the app is not actually recording as far as I can tell.

**Comment by IliasHad** [comment]
@polyglotdev  Thank you for using Makerlapse. Do you have a folder generated when you start recording like this one 2020-07-20-09-13-44 in you Makerlapse root folder
